### PR TITLE
 Run free automated flake8 testing on pull requests

### PR DESCRIPTION
**Pull request by cclauss**
The Travis Continuous Integration service is free for all open source projects like this one.  This configuration will enable Travis CI to run tests on all pull requests before they are merged.  The owner of this repo would need to go to https://travis-ci.org/profile (log in via GitHub) and flip the repository switch __on__ to enable free, automated flake8 testing of each pull request.

### CODE REVIEW

**Comment by cclauss** [comment]
flake8 testing of https://github.com/tensorlang/tensorlang on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/__init__.py:14:5: F821 undefined name 'dist'
del dist
    ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/__init__.py:15:5: F821 undefined name 'finder'
del finder
    ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/__init__.py:16:5: F821 undefined name 'freezer'
del freezer
    ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/setupwriter.py:6:13: F821 undefined name 'raw_input'
    input = raw_input
            ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/initscripts/SharedLib.py:18:42: F821 undefined name 'DIR_NAME'
os.environ["TCL_LIBRARY"] = os.path.join(DIR_NAME, "tcl")
                                         ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/initscripts/SharedLib.py:19:41: F821 undefined name 'DIR_NAME'
os.environ["TK_LIBRARY"] = os.path.join(DIR_NAME, "tk")
                                        ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/initscripts/SharedLibSource.py:19:34: F821 undefined name 'FILE_NAME'
baseName, ext = os.path.splitext(FILE_NAME)
                                 ^
./core/native/vendor/cx_Freeze-5.0.1/cx_Freeze/initscripts/SharedLibSource.py:21:32: F821 undefined name 'file'
sys.path = [s.strip() for s in file(pathFileName).read().splitlines()] + \
                               ^
./core/python/src/nao/cli.py:202:43: F821 undefined name 'source'
      p.put_source(package_name + ".nao", source)
                                          ^
./core/python/src/nao/cli.py:351:28: F821 undefined name 'log_dir_fn'
      log_dir_fn=lambda x: log_dir_fn(x)(),
                           ^
./core/python/src/nao/cli.py:359:28: F821 undefined name 'log_dir_fn'
      log_dir_fn=lambda x: log_dir_fn(x)(),
                           ^
./core/python/src/nao/cli.py:417:28: F821 undefined name 'log_dir_fn'
      log_dir_fn=lambda x: log_dir_fn(x)(),
                           ^
./core/python/src/nao/compiler/primitive_function.py:27:30: F821 undefined name 'partial'
    return PrimitiveFunction(partial(self._fn, **attrs))
                             ^
./core/python/src/nao/compiler/nao/graph_loop.py:45:25: F821 undefined name 'control_flow_pb2'
    while_context_def = control_flow_pb2.WhileContextDef()
                        ^
./core/python/src/nao/tool/graph_repl.py:47:35: F821 undefined name 'sess'
      threads = qr.create_threads(sess, coord=self._coord, daemon=True, start=True)
                                  ^
./core/python/src/nao/tool/summary_format.py:85:53: F821 undefined name 'self'
  return [histo_ev, lambda x: _CompressHistogram(x, self._compression_bps)]
                                                    ^
16    F821 undefined name 'dist'
```

**Comment by cclauss** [comment]
Some of these issues could be solved by incorporating cx_Freeze-5.1.1 (instead of 5.0.1) from https://github.com/anthony-tuininga/cx_Freeze however the last five are from this codebase and I do not know how to solve them.

**Comment by ajbouh** [comment]
Thanks for the list. I fixed all the nao-related ones.

I included the source to cx_Freeze because needed to make some modifications to it for the build to work. The relevant series of changes are here: https://github.com/tensorlang/tensorlang/commits/cac1527c53dce777a32db14df1baa31fe2180a17/tools/cx_Freeze-5.0.1

I haven't had a chance to update to the latest cx_Freeze yet though.

**Comment by cclauss** [comment]
Also see my PRs on cf_Freeze https://github.com/anthony-tuininga/cx_Freeze/pulls/cclauss

**Comment by cclauss** [comment]
Flake8 tests pass on Python 3.

**Comment by ajbouh** [comment]
Cool, thanks!

**Pull request closed without merging**
